'use client';
import { useEffect, useMemo, useState } from 'react';
import { MARKET_ORDER, calculateProfit, outcomeFractionForScore, priceCLV, extractLineToken, resultLabel, validateMarketPair, marketIsOpen } from '../lib/markets.js';

const VERSION='3.0.1';
const STORAGE='mlb-positive-ev-v3';
const DEFAULT_SETTINGS={unitValue:10000,rebateRate:.015,defaultWater:.95,candidateThreshold:7.2,strongestThreshold:8.5};
const EMPTY={locks:[],analyses:{},bets:[],settings:DEFAULT_SETTINGS};
const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n)||0);
const pct=n=>`${((Number(n)||0)*100).toFixed(2)}%`;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
async function readDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function compressImage(file){const src=await readDataURL(file);return new Promise(resolve=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.76))};img.onerror=()=>resolve(src);img.src=src})}
async function requestJSON(url,options={},timeout=120000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal,cache:'no-store'});const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error(`伺服器回傳格式錯誤（${r.status}）`)}if(!r.ok||j.ok===false)throw Error(j.error||`HTTP ${r.status}`);return j}finally{clearTimeout(t)}}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function blankGame(game,water=.95){return{id:uid(),away:game?.away||'',home:game?.home||'',gamePk:game?.gamePk||null,matchedGame:game||null,confidence:0,markets:MARKET_ORDER.map(m=>({market:m,directions:[{pick:'',water,confidence:0},{pick:'',water,confidence:0}]}))}}
function flattenMarkets(g){return MARKET_ORDER.flatMap(m=>{const x=g.markets?.find(y=>y.market===m);if(!marketIsOpen(x?.directions||[]))return[];return(x?.directions||[]).slice(0,2).filter(d=>String(d?.pick||'').trim()).map(d=>({market:m,pick:String(d.pick||''),water:Number(d.water),confidence:Number(d.confidence||0)}))})}
function mergeVision(rows){const map=new Map();for(const r of rows){const key=String(r.gamePk||`${r.away}-${r.home}`).toLowerCase();if(!map.has(key)){map.set(key,{...r,id:uid()});continue}const old=map.get(key);map.set(key,{...old,markets:MARKET_ORDER.map(m=>{const a=old.markets?.find(x=>x.market===m),b=r.markets?.find(x=>x.market===m);return{market:m,directions:[0,1].map(i=>{const x=a?.directions?.[i],y=b?.directions?.[i];return Number(y?.confidence||0)>Number(x?.confidence||0)?y:x||y||{pick:'',water:.95,confidence:0}})}})})}return[...map.values()]}
export default function Home(){
 const[tab,setTab]=useState('today'),[date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date())),[games,setGames]=useState([]),[loadingGames,setLoadingGames]=useState(false),[health,setHealth]=useState(null);const[store,setStore]=useState(EMPTY),[ready,setReady]=useState(false),[images,setImages]=useState([]),[visionStatus,setVisionStatus]=useState(''),[visionBusy,setVisionBusy]=useState(false),[manualText,setManualText]=useState(''),[manualGamePk,setManualGamePk]=useState(''),[parsed,setParsed]=useState([]),[selected,setSelected]=useState(0);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved)setStore({...EMPTY,...saved,settings:{...DEFAULT_SETTINGS,...saved.settings}})}catch{}setReady(true);loadGames();requestJSON('/api/health').then(setHealth).catch(()=>setHealth({ok:false}))},[]);useEffect(()=>{if(ready)localStorage.setItem(STORAGE,JSON.stringify(store))},[store,ready]);
 async function loadGames(){setLoadingGames(true);try{const j=await requestJSON(`/api/mlb?date=${date}`);setGames(j.games||[])}catch(e){alert(`賽程載入失敗：${e.message}`)}finally{setLoadingGames(false)}}
 async function chooseImages(files){const list=[...(files||[])].slice(0,8);setVisionStatus('正在壓縮圖片…');const rows=[];for(let i=0;i<list.length;i++){const f=list[i];rows.push({id:uid(),name:f.name,preview:URL.createObjectURL(f),data:await compressImage(f),size:f.size});setVisionStatus(`正在處理 ${i+1}/${list.length}`)}setImages(rows);setVisionStatus(`已準備 ${rows.length} 張圖片`)}
 async function recognize(){if(!images.length)return alert('請先選擇盤口截圖');if(visionBusy)return;setVisionBusy(true);const all=[];try{for(let i=0;i<images.length;i++){setVisionStatus(`AI 辨識中 ${i+1}/${images.length}…`);let j;try{j=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:[images[i].data],schedule:games,defaultWater:store.settings.defaultWater})})}catch(e){if(/Load failed|fetch|Network|逾時|abort/i.test(e.message)){setVisionStatus(`第 ${i+1} 張連線重試…`);await new Promise(r=>setTimeout(r,1000));j=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:[images[i].data],schedule:games,defaultWater:store.settings.defaultWater})})}else throw e}all.push(...(j.games||[]))}const merged=mergeVision(all);if(!merged.length)throw Error('沒有辨識到任何場次');setParsed(merged);setSelected(0);setVisionStatus(`辨識完成：${merged.length} 場`);setTab('confirm')}catch(e){setVisionStatus(`辨識失敗：${e.message}`)}finally{setVisionBusy(false)}}
 async function parseText(){if(!manualText.trim())return alert('請先貼上盤口文字');setVisionBusy(true);setVisionStatus('AI 正在解析文字…');try{const j=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:manualText,schedule:games,defaultWater:store.settings.defaultWater})});const rows=mergeVision(j.games||[]);if(!rows.length)throw Error('沒有解析到場次');setParsed(rows);setSelected(0);setVisionStatus(`解析完成：${rows.length} 場`);setTab('confirm')}catch(e){setVisionStatus(`解析失敗：${e.message}`)}finally{setVisionBusy(false)}}
 function addManual(){const g=games.find(x=>String(x.gamePk)===String(manualGamePk));if(!g)return alert('請先選擇一場 MLB 賽事');setParsed(p=>[...p,blankGame(g,store.settings.defaultWater)]);setSelected(parsed.length);setTab('confirm')}
 const cur=parsed[selected];function updateCur(fn){setParsed(p=>p.map((g,i)=>i===selected?fn(g):g))}function setMatch(pk){const g=games.find(x=>String(x.gamePk)===String(pk))||null;updateCur(x=>({...x,gamePk:g?.gamePk||null,matchedGame:g,away:g?.away||x.away,home:g?.home||x.home}))}function editDirection(market,index,key,value){updateCur(g=>({...g,markets:g.markets.map(m=>m.market!==market?m:{...m,directions:m.directions.map((d,i)=>i===index?{...d,[key]:key==='water'?Number(value):value}:d)})}))}
 const currentErrors=useMemo(()=>{if(!cur)return[];const e=[];if(!cur.matchedGame)e.push('尚未配對 MLB 官方賽事');for(const m of MARKET_ORDER){const x=cur.markets?.find(y=>y.market===m);e.push(...validateMarketPair(m,x?.directions||[]).map(v=>`${m}：${v}`))}return[...new Set(e)]},[cur]);
 function lockCurrent(){if(!cur)return;if(currentErrors.length)return alert(currentErrors.join('\n'));const markets=flattenMarkets(cur);if(!markets.length)return alert('這場目前沒有任何已開盤市場，無需鎖定');const lock={id:uid(),sourceId:cur.id,lockedAt:new Date().toISOString(),game:cur.matchedGame,markets,version:1,status:'locked'};setStore(s=>({...s,locks:[lock,...s.locks.filter(x=>String(x.game.gamePk)!==String(lock.game.gamePk))]}));alert(`盤口已鎖定：${new Set(markets.map(x=>x.market)).size} 個市場／${markets.length} 個方向`)}
 async function analyze(lock){setStore(s=>({...s,analyses:{...s.analyses,[lock.id]:{loading:true}}}));try{const j=await requestJSON('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:lock.game,markets:lock.markets,settings:store.settings})},120000);setStore(s=>({...s,analyses:{...s.analyses,[lock.id]:j}}));setTab('analysis')}catch(e){setStore(s=>({...s,analyses:{...s.analyses,[lock.id]:{error:e.message}}}))}}
 function addBet(game,result){const unit=1,stake=store.settings.unitValue;const bet={id:uid(),createdAt:new Date().toISOString(),gamePk:game.gamePk,away:game.away,home:game.home,game:`${game.away} @ ${game.home}`,market:result.market,pick:result.pick,water:result.water,score:result.score,unit,stake,result:'未結算',fraction:null,profit:0,rebate:0,awayRuns:'',homeRuns:'',awayFirst5:'',homeFirst5:'',closeWater:'',closePick:'',clv:null};setStore(s=>({...s,bets:[bet,...s.bets]}))}function updateBet(id,patch){setStore(s=>({...s,bets:s.bets.map(b=>b.id===id?{...b,...patch}:b)}))}function settleBet(b,awayRuns=b.market.includes('上半')?b.awayFirst5:b.awayRuns,homeRuns=b.market.includes('上半')?b.homeFirst5:b.homeRuns){const f=outcomeFractionForScore(b.pick,Number(awayRuns),Number(homeRuns),b.away,b.home);if(f==null)return alert('盤口或球隊名稱無法結算');const stake=Number(b.unit||1)*store.settings.unitValue,calc=calculateProfit({stake,water:b.water,fraction:f,rebateRate:store.settings.rebateRate}),sameLine=!b.closePick||extractLineToken(b.closePick)===extractLineToken(b.pick),clv=b.closeWater&&sameLine?priceCLV(b.water,b.closeWater):null;const patch=b.market.includes('上半')?{awayFirst5:Number(awayRuns),homeFirst5:Number(homeRuns)}:{awayRuns:Number(awayRuns),homeRuns:Number(homeRuns)};updateBet(b.id,{...patch,stake,fraction:f,result:resultLabel(f),profit:calc.profit,rebate:calc.rebate,clv})}async function autoSettle(b){try{const j=await requestJSON(`/api/result?gamePk=${b.gamePk}`);if(!j.final)return alert(`比賽尚未結束：${j.status}`);settleBet(b,b.market.includes('上半')?j.awayFirst5:j.awayRuns,b.market.includes('上半')?j.homeFirst5:j.homeRuns)}catch(e){alert(e.message)}}function removeBet(id){if(confirm('刪除這筆下注？'))setStore(s=>({...s,bets:s.bets.filter(b=>b.id!==id)}))}
 const gameSummary=useMemo(()=>games.map(g=>{const lock=store.locks.find(x=>String(x.game.gamePk)===String(g.gamePk)),a=lock&&store.analyses[lock.id],scores=a?.analysis?.results?.map(x=>x.score)||[];return{...g,locked:!!lock,analyzed:!!a?.ok,highest:scores.length?Math.max(...scores):null}}),[games,store]);const allResults=useMemo(()=>Object.values(store.analyses).flatMap(a=>a?.analysis?.results||[]),[store.analyses]);const perf=useMemo(()=>{const settled=store.bets.filter(b=>b.fraction!=null),profit=settled.reduce((a,b)=>a+Number(b.profit||0),0),risk=settled.reduce((a,b)=>a+Number(b.stake||0),0),rebate=settled.reduce((a,b)=>a+Number(b.rebate||0),0),clv=settled.filter(b=>b.clv!=null);return{settled,profit,risk,rebate,roi:risk?profit/risk:0,avgClv:clv.length?clv.reduce((a,b)=>a+b.clv,0)/clv.length:null,w:settled.filter(b=>Number(b.fraction)>0).length,l:settled.filter(b=>Number(b.fraction)<0).length,p:settled.filter(b=>Number(b.fraction)===0).length}},[store.bets]);function exportJSON(){download(`mlb-positive-ev-${Date.now()}.json`,JSON.stringify(store,null,2))}function exportCSV(){const head=['時間','比賽','市場','投注','水位','評分','Unit','結果','盈虧','退水','CLV'];const rows=store.bets.map(b=>[b.createdAt,b.game,b.market,b.pick,b.water,b.score,b.unit,b.result,b.profit,b.rebate,b.clv]);download(`mlb-bets-${Date.now()}.csv`,[head,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}async function importJSON(file){try{const j=JSON.parse(await file.text());setStore({...EMPTY,...j,settings:{...DEFAULT_SETTINGS,...j.settings}});alert('備份已還原')}catch{alert('備份檔格式錯誤')}}const scoreGroups=[['8.5+',b=>b.score>=8.5],['8.0–8.4',b=>b.score>=8&&b.score<8.5],['7.2–7.9',b=>b.score>=7.2&&b.score<8],['<7.2',b=>b.score<7.2]];
 return <main className="shell"><header className="header"><div><div className="eyebrow">PRIVATE ANALYTICS</div><h1>⚾ MLB Positive EV</h1><p>截圖辨識 → 盤口鎖定 → MLB 資料 → 實際開盤市場 EV → 下注績效</p></div><div className="headerRight"><span className={`health ${health?.ok&&health?.aiGatewayConfigured?'ok':'warn'}`}>{health?.ok?(health.aiGatewayConfigured?'AI 正常':'AI 未設定'):'檢查中'}</span><span className="badge">v{VERSION}</span></div></header><nav className="tabs">{[['today','今日賽事'],['upload','📷 上傳'],['confirm','盤口確認'],['analysis','分析結果'],['bets','下注紀錄'],['perf','績效'],['settings','設定']].map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n