'use client';
import {useEffect,useMemo,useState} from 'react';
const ORDER=['全場讓分','全場大小','上半讓分','上半大小'];
const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`, ev=v=>`${Number(v||0)>=0?'+':''}${(Number(v||0)*100).toFixed(2)}%`;
async function dataUrl(f){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
export default function Home(){const[tab,setTab]=useState('today'),[date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date())),[games,setGames]=useState([]),[images,setImages]=useState([]),[status,setStatus]=useState(''),[parsed,setParsed]=useState([]),[sel,setSel]=useState(0),[locked,setLocked]=useState([]),[analyses,setAnalyses]=useState({}),[bets,setBets]=useState([]);
useEffect(()=>{try{setBets(JSON.parse(localStorage.getItem('mlb-bets-v2')||'[]'))}catch{}loadGames()},[]);useEffect(()=>{localStorage.setItem('mlb-bets-v2',JSON.stringify(bets))},[bets]);
async function loadGames(){try{const j=await(await fetch(`/api/mlb?date=${date}`)).json();if(!j.ok)throw Error(j.error);setGames(j.games||[])}catch(e){alert(e.message)}}
async function pick(fs){const rows=[];for(const f of [...fs].slice(0,8))rows.push({name:f.name,url:URL.createObjectURL(f),data:await dataUrl(f)});setImages(rows);setStatus(`${rows.length} 張圖片已讀取`)}
async function vision(){if(!images.length)return alert('請先選擇盤口截圖');setStatus('AI 正在辨識盤口…');try{const j=await(await fetch('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:images.map(x=>x.data)})})).json();if(!j.ok)throw Error(j.error);const ps=(j.parsed?.games||[]).map((g,i)=>({...g,id:`p${Date.now()}-${i}`,matchedGame:null}));setParsed(ps);setSel(0);setStatus(`辨識完成：${ps.length} 場`);setTab('confirm')}catch(e){setStatus(`辨識失敗：${e.message}`)}}
const cur=parsed[sel];const update=fn=>setParsed(p=>p.map((g,i)=>i===sel?fn(g):g));function dir(m,di,k,v){update(g=>({...g,markets:(g.markets||[]).map(x=>x.market===m?{...x,directions:(x.directions||[]).map((d,i)=>i===di?{...d,[k]:v}:d)}:x)}))}function match(pk){update(g=>({...g,matchedGame:games.find(x=>String(x.gamePk)===String(pk))||null}))}function lock(){if(!cur?.matchedGame)return alert('請先選 MLB 賽事');const ms=[];for(const m of ORDER){const x=(cur.markets||[]).find(y=>y.market===m);for(const d of x?.directions||[])if(d?.pick)ms.push({market:m,pick:d.pick,water:Number(d.water||.95),confidence:Number(d.confidence||0)})}if(!ms.length)return alert('沒有盤口');setLocked(p=>[...p.filter(x=>x.id!==cur.id),{id:cur.id,game:cur.matchedGame,markets:ms}]);alert('盤口已鎖定')}
async function analyze(row){setAnalyses(a=>({...a,[row.id]:{loading:true}}));try{const j=await(await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:row.game,markets:row.markets})})).json();if(!j.ok)throw Error(j.error);setAnalyses(a=>({...a,[row.id]:j}));setTab('analysis')}catch(e){setAnalyses(a=>({...a,[row.id]:{error:e.message}}))}}
function bet(game,r){setBets(p=>[{id:crypto.randomUUID(),time:new Date().toISOString(),game:`${game.away} @ ${game.home}`,market:r.market,pick:r.pick,water:r.water,score:r.score,unit:1,result:'未結算',profit:0},...p])}function settle(id,res){setBets(p=>p.map(b=>{if(b.id!==id)return b;const u=Number(b.unit||1),w=Number(b.water||.95),profit=res==='勝'?u*w:res==='敗'?-u:res==='半勝'?u*w/2:res==='半敗'?-u/2:0;return{...b,result:res,profit}}))}const stats=useMemo(()=>{const d=bets.filter(b=>b.result!=='未結算'),profit=d.reduce((a,b)=>a+Number(b.profit||0),0),risk=d.reduce((a,b)=>a+Number(b.unit||0),0);return{n:bets.length,w:d.filter(b=>b.result==='勝').length,l:d.filter(b=>b.result==='敗').length,p:d.filter(b=>b.result==='走水').length,profit,roi:risk?profit/risk:0}},[bets]);
return <main className="shell"><header className="header"><div><div className="eyebrow">PRIVATE ANALYTICS</div><h1>⚾ MLB Positive EV</h1><p>盤口截圖 → AI 辨識 → 鎖定 → MLB 資料 → 8 方向模型 → 下注績效</p></div><div className="badge">v1.0</div></header><nav className="tabs">{[['today','今日賽事'],['upload','📷 上傳'],['confirm','盤口確認'],['analysis','分析結果'],['bets','下注紀錄'],['perf','績效']].map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</nav>
{tab==='today'&&<section><div className="card row between"><div><h2>今日 MLB Dashboard</h2><p className="muted">MLB Stats API 即時賽程與 probable pitchers</p></div><div className="row"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="primary" onClick={loadGames}>重新載入</button></div></div><div className="card">{games.map(g=><div className="gameRow" key={g.gamePk}><div><b>{g.away} @ {g.home}</b><div className="muted">{new Date(g.gameDate).toLocaleString('zh-TW')}｜{g.venue}</div><div className="muted">先發：{g.awayProbable||'未公布'} vs {g.homeProbable||'未公布'}</div></div><span className="pill">{g.status}</span></div>)}</div></section>}
{tab==='upload'&&<section><div className="card"><h2>上傳信用盤截圖</h2><label className="drop">點這裡從 iPhone 相簿選擇截圖<input type="file" accept="image/*" multiple onChange={e=>pick(e.target.files)}/><span>最多 8 張</span></label><div className="previews">{images.map((x,i)=><div className="preview" key={i}><img src={x.url} alt="盤口"/><small>{x.name}</small></div>)}</div><div className="status">{status||'尚未選圖'}</div><button className="primary full" onClick={vision}>開始 AI 辨識盤口</button></div></section>}
{tab==='confirm'&&<section><div className="card"><h2>盤口確認與鎖定</h2>{!parsed.length?<p>尚無辨識結果</p>:<><div className="chips">{parsed.map((g,i)=><button className={i===sel?'chip activeChip':'chip'} key={g.id} onClick={()=>setSel(i)}>{g.away||'?'} @ {g.home||'?'}</button>)}</div><label>配對 MLB 賽事<select value={cur?.matchedGame?.gamePk||''} onChange={e=>match(e.target.value)}><option value="">請選擇</option>{games.map(g=><option key={g.gamePk} value={g.gamePk}>{g.away} @ {g.home}</option>)}</select></label>{ORDER.map(m=>{const x=(cur?.markets||[]).find(y=>y.market===m)||{directions:[]},ds=[...(x.directions||[])];while(ds.length<2)ds.push({pick:'',water:.95});return <div className="market" key={m}><h3>{m}</h3><div className="two">{ds.slice(0,2).map((d,i)=><div key={i}><label>方向＋盤口<input value={d.pick||''} onChange={e=>dir(m,i,'pick',e.target.value)}/></label><label>水位<input type="number" step=".001" value={d.water??.95} onChange={e=>dir(m,i,'water',e.target.value)}/></label></div>)}</div></div>})}<button className="primary full" onClick={lock}>🔒 確認並鎖定</button></>}</div><div className="card"><h2>已鎖定</h2>{locked.map(r=><div className="locked" key={r.id}><b>{r.game.away} @ {r.game.home}</b><button className="primary" onClick={()=>analyze(r)}>開始分析</button></div>)}</div></section>}
{tab==='analysis'&&<section>{locked.map(row=>{const a=analyses[row.id];if(!a?.ok)return null;return <div className="card" key={row.id}><h2>{row.game.away} @ {row.game.home}</h2>{ORDER.map(m=><div className="market" key={m}><h3>{m}</h3>{a.analysis.results.filter(x=>x.market===m).map((r,i)=><div className={`result ${r.score>=8.5?'best':r.score>=7.2?'candidate':''}`} key={i}><div><span className="score">{r.score.toFixed(1)}</span>｜{r.pick}｜{Number(r.water).toFixed(3)} <span className="tag">{r.tag}</span><small>模型過盤率 {pct(r.modelProbability)}｜EV {ev(r.ev)}｜穩健 EV {ev(r.robustEV)}｜加權 EV {ev(r.weightedEV)}</small></div><button onClick={()=>bet(row.game,r)}>已下注</button></div>)}</div>)}</div>})}</section>}
{tab==='bets'&&<section><div className="card"><h2>下注紀錄</h2><div className="tableWrap"><table><tbody>{bets.map(b=><tr key={b.id}><td>{b.game}</td><td>{b.market}<br/>{b.pick}</td><td>{Number(b.score).toFixed(1)}</td><td><select value={b.result} onChange={e=>settle(b.id,e.target.value)}><option>未結算</option><option>勝</option><option>敗</option><option>走水</option><option>半勝</option><option>半敗</option></select></td><td>{Number(b.profit||0).toFixed(2)} U</td></tr>)}</tbody></table></div></div></section>}
{tab==='perf'&&<section><div className="card"><h2>績效 Dashboard</h2><div className="signals"><div><span>總下注</span><b>{stats.n}</b></div><div><span>勝/敗/走</span><b>{stats.w}/{stats.l}/{stats.p}</b></div><div><span>ROI</span><b>{(stats.roi*100).toFixed(2)}%</b></div><div><span>總盈虧</span><b>{stats.profit.toFixed(2)} U</b></div></div></div></section>}</main>}
