'use client';
import { useEffect, useMemo, useState } from 'react';
import {
  MARKET_ORDER,
  calculateProfit,
  outcomeFractionForScore,
  priceCLV,
  extractLineToken,
  resultLabel,
  validateMarketPair,
  marketIsOpen,
} from '../lib/markets.js';
import { translateTeamText } from '../lib/i18n.js';

const VERSION='4.0.0';
const STORAGE='mlb-positive-ev-v4';
const LEGACY_STORAGE='mlb-positive-ev-v3';
const DEFAULT_SETTINGS={unitValue:10000,rebateRate:.015,defaultWater:.95,candidateThreshold:7.2,strongestThreshold:8.5};
const EMPTY={locks:[],analyses:{},bets:[],settings:DEFAULT_SETTINGS};
const money=value=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(value)||0);
const pct=value=>`${((Number(value)||0)*100).toFixed(2)}%`;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const matchup=game=>`${translateTeamText(game?.away||'')} 對 ${translateTeamText(game?.home||'')}`;

async function readDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function compressImage(file){const source=await readDataURL(file);return new Promise(resolve=>{const image=new Image();image.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(image.width,image.height)),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(image,0,0,width,height);resolve(canvas.toDataURL('image/jpeg',.76))};image.onerror=()=>resolve(source);image.src=source})}
async function requestJSON(url,options={},timeout=120000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{...options,signal:controller.signal,cache:'no-store'});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw Error(`伺服器回傳格式錯誤（${response.status}）`)}if(!response.ok||data.ok===false)throw Error(data.error||`請求失敗（${response.status}）`);return data}finally{clearTimeout(timer)}}
function download(name,text,type='application/json'){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function blankGame(game,water=.95){return{id:uid(),away:game?.away||'',home:game?.home||'',gamePk:game?.gamePk||null,matchedGame:game||null,confidence:0,markets:MARKET_ORDER.map(market=>({market,directions:[{pick:'',water,confidence:0},{pick:'',water,confidence:0}]}))}}
function flattenMarkets(game){return MARKET_ORDER.flatMap(market=>{const row=game.markets?.find(item=>item.market===market);if(!marketIsOpen(row?.directions||[]))return[];return(row?.directions||[]).slice(0,2).filter(direction=>String(direction?.pick||'').trim()).map(direction=>({market,pick:String(direction.pick||''),water:Number(direction.water),confidence:Number(direction.confidence||0)}))})}
function mergeVision(rows){const map=new Map();for(const row of rows){const key=String(row.gamePk||`${row.away}-${row.home}`).toLowerCase();if(!map.has(key)){map.set(key,{...row,id:uid()});continue}const previous=map.get(key);map.set(key,{...previous,markets:MARKET_ORDER.map(market=>{const a=previous.markets?.find(item=>item.market===market),b=row.markets?.find(item=>item.market===market);return{market,directions:[0,1].map(index=>{const left=a?.directions?.[index],right=b?.directions?.[index];return Number(right?.confidence||0)>Number(left?.confidence||0)?right:left||right||{pick:'',water:.95,confidence:0}})}})})}return[...map.values()]}

export default function Home(){
  const[tab,setTab]=useState('today'),[date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date())),[games,setGames]=useState([]),[loadingGames,setLoadingGames]=useState(false),[health,setHealth]=useState(null);
  const[store,setStore]=useState(EMPTY),[ready,setReady]=useState(false),[images,setImages]=useState([]),[visionStatus,setVisionStatus]=useState(''),[visionBusy,setVisionBusy]=useState(false),[manualText,setManualText]=useState(''),[manualGamePk,setManualGamePk]=useState(''),[parsed,setParsed]=useState([]),[selected,setSelected]=useState(0);

  useEffect(()=>{
    try{
      let saved=JSON.parse(localStorage.getItem(STORAGE)||'null');
      if(!saved){const legacy=JSON.parse(localStorage.getItem(LEGACY_STORAGE)||'null');if(legacy)saved={...EMPTY,bets:Array.isArray(legacy.bets)?legacy.bets:[],settings:{...DEFAULT_SETTINGS,...legacy.settings},locks:[],analyses:{}}}
      if(saved)setStore({...EMPTY,...saved,settings:{...DEFAULT_SETTINGS,...saved.settings},locks:Array.isArray(saved.locks)?saved.locks:[],analyses:saved.analyses||{},bets:Array.isArray(saved.bets)?saved.bets:[]});
    }catch{}
    setReady(true);loadGames();requestJSON('/api/health').then(setHealth).catch(()=>setHealth({ok:false}));
  },[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORAGE,JSON.stringify(store))},[store,ready]);

  async function loadGames(){setLoadingGames(true);try{const data=await requestJSON(`/api/mlb?date=${date}`);setGames(data.games||[])}catch(error){alert(`賽程載入失敗：${error.message}`)}finally{setLoadingGames(false)}}
  async function chooseImages(files){const list=[...(files||[])].slice(0,8);setVisionStatus('正在壓縮圖片…');const rows=[];for(let index=0;index<list.length;index+=1){const file=list[index];rows.push({id:uid(),name:file.name,preview:URL.createObjectURL(file),data:await compressImage(file),size:file.size});setVisionStatus(`正在處理第 ${index+1} 張，共 ${list.length} 張`)}setImages(rows);setVisionStatus(`已準備 ${rows.length} 張圖片`)}
  async function recognize(){if(!images.length)return alert('請先選擇盤口截圖');if(visionBusy)return;setVisionBusy(true);const all=[];try{for(let index=0;index<images.length;index+=1){setVisionStatus(`人工智慧辨識中：第 ${index+1} 張，共 ${images.length} 張`);let data;try{data=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:[images[index].data],schedule:games,defaultWater:store.settings.defaultWater})})}catch(error){if(/載入失敗|Load failed|fetch|Network|逾時|abort/i.test(error.message)){setVisionStatus(`第 ${index+1} 張連線不穩，正在自動重試…`);await new Promise(resolve=>setTimeout(resolve,1000));data=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:[images[index].data],schedule:games,defaultWater:store.settings.defaultWater})})}else throw error}all.push(...(data.games||[]))}const merged=mergeVision(all);if(!merged.length)throw Error('沒有辨識到任何場次');setParsed(merged);setSelected(0);setVisionStatus(`辨識完成：共 ${merged.length} 場`);setTab('confirm')}catch(error){setVisionStatus(`辨識失敗：${error.message}`)}finally{setVisionBusy(false)}}
  async function parseText(){if(!manualText.trim())return alert('請先貼上盤口文字');setVisionBusy(true);setVisionStatus('正在解析盤口文字…');try{const data=await requestJSON('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:manualText,schedule:games,defaultWater:store.settings.defaultWater})});const rows=mergeVision(data.games||[]);if(!rows.length)throw Error('沒有解析到場次');setParsed(rows);setSelected(0);setVisionStatus(`解析完成：共 ${rows.length} 場`);setTab('confirm')}catch(error){setVisionStatus(`解析失敗：${error.message}`)}finally{setVisionBusy(false)}}
  function addManual(){const game=games.find(item=>String(item.gamePk)===String(manualGamePk));if(!game)return alert('請先選擇一場 MLB 賽事');setParsed(previous=>[...previous,blankGame(game,store.settings.defaultWater)]);setSelected(parsed.length);setTab('confirm')}

  const cur=parsed[selected];
  function updateCur(updater){setParsed(previous=>previous.map((game,index)=>index===selected?updater(game):game))}
  function setMatch(gamePk){const game=games.find(item=>String(item.gamePk)===String(gamePk))||null;updateCur(current=>({...current,gamePk:game?.gamePk||null,matchedGame:game,away:game?.away||current.away,home:game?.home||current.home}))}
  function editDirection(market,index,key,value){updateCur(game=>({...game,markets:game.markets.map(row=>row.market!==market?row:{...row,directions:row.directions.map((direction,directionIndex)=>{if(directionIndex!==index)return direction;const next={...direction,[key]:key==='water'?Number(value):value};if(key==='pick')next.confidence=String(value).trim()?1:0;return next})})}))}
  const currentErrors=useMemo(()=>{if(!cur)return[];const errors=[];if(!cur.matchedGame)errors.push('尚未配對 MLB 官方賽事');for(const market of MARKET_ORDER){const row=cur.markets?.find(item=>item.market===market);errors.push(...validateMarketPair(market,row?.directions||[]).map(error=>`${market}：${error}`))}return[...new Set(errors)]},[cur]);
  const currentOpenMarkets=useMemo(()=>cur?MARKET_ORDER.filter(market=>marketIsOpen(cur.markets?.find(item=>item.market===market)?.directions||[])):[],[cur]);
  const currentDirectionCount=useMemo(()=>cur?flattenMarkets(cur).length:0,[cur]);
  function lockCurrent(){if(!cur)return;if(currentErrors.length)return alert(currentErrors.join('\n'));const markets=flattenMarkets(cur);if(!markets.length)return alert('這場目前沒有任何已開盤市場，不需要鎖定');const lock={id:uid(),sourceId:cur.id,lockedAt:new Date().toISOString(),game:cur.matchedGame,markets,version:2,status:'locked'};setStore(current=>({...current,locks:[lock,...current.locks.filter(item=>String(item.game.gamePk)!==String(lock.game.gamePk))]}));alert(`盤口已鎖定：${new Set(markets.map(item=>item.market)).size} 個市場、${markets.length} 個方向`)}
  async function analyze(lock){setStore(current=>({...current,analyses:{...current.analyses,[lock.id]:{loading:true}}}));try{const data=await requestJSON('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:lock.game,markets:lock.markets,settings:store.settings})},120000);setStore(current=>({...current,analyses:{...current.analyses,[lock.id]:data}}));setTab('analysis')}catch(error){setStore(current=>({...current,analyses:{...current.analyses,[lock.id]:{error:error.message}}}))}}

  function addBet(game,result){const unit=1,stake=store.settings.unitValue;const bet={id:uid(),createdAt:new Date().toISOString(),gamePk:game.gamePk,away:game.away,home:game.home,game:matchup(game),market:result.market,pick:result.pick,water:result.water,score:result.score,unit,stake,result:'未結算',fraction:null,profit:0,rebate:0,awayRuns:'',homeRuns:'',awayFirst5:'',homeFirst5:'',closeWater:'',closePick:'',clv:null};setStore(current=>({...current,bets:[bet,...current.bets]}))}
  function updateBet(id,patch){setStore(current=>({...current,bets:current.bets.map(bet=>bet.id===id?{...bet,...patch}:bet)}))}
  function settleBet(bet,awayRuns=bet.market.includes('上半')?bet.awayFirst5:bet.awayRuns,homeRuns=bet.market.includes('上半')?bet.homeFirst5:bet.homeRuns){const fraction=outcomeFractionForScore(bet.pick,Number(awayRuns),Number(homeRuns),bet.away,bet.home);if(fraction==null)return alert('盤口或球隊名稱無法結算');const stake=Number(bet.unit||1)*store.settings.unitValue,calculation=calculateProfit({stake,water:bet.water,fraction,rebateRate:store.settings.rebateRate}),sameLine=!bet.closePick||extractLineToken(bet.closePick)===extractLineToken(bet.pick),clv=bet.closeWater&&sameLine?priceCLV(bet.water,bet.closeWater):null;const scorePatch=bet.market.includes('上半')?{awayFirst5:Number(awayRuns),homeFirst5:Number(homeRuns)}:{awayRuns:Number(awayRuns),homeRuns:Number(homeRuns)};updateBet(bet.id,{...scorePatch,stake,fraction,result:resultLabel(fraction),profit:calculation.profit,rebate:calculation.rebate,clv})}
  async function autoSettle(bet){try{const data=await requestJSON(`/api/result?gamePk=${bet.gamePk}`);if(!data.final)return alert(`比賽尚未結束：${data.status}`);settleBet(bet,bet.market.includes('上半')?data.awayFirst5:data.awayRuns,bet.market.includes('上半')?data.homeFirst5:data.homeRuns)}catch(error){alert(error.message)}}
  function removeBet(id){if(confirm('確定刪除這筆下注紀錄？'))setStore(current=>({...current,bets:current.bets.filter(bet=>bet.id!==id)}))}

  const gameSummary=useMemo(()=>games.map(game=>{const lock=store.locks.find(item=>String(item.game.gamePk)===String(game.gamePk)),analysis=lock&&store.analyses[lock.id],scores=analysis?.analysis?.results?.map(result=>result.score)||[];return{...game,locked:!!lock,analyzed:!!analysis?.ok,highest:scores.length?Math.max(...scores):null}}),[games,store]);
  const allResults=useMemo(()=>Object.values(store.analyses).flatMap(analysis=>analysis?.analysis?.results||[]),[store.analyses]);
  const perf=useMemo(()=>{const settled=store.bets.filter(bet=>bet.fraction!=null),profit=settled.reduce((sum,bet)=>sum+Number(bet.profit||0),0),risk=settled.reduce((sum,bet)=>sum+Number(bet.stake||0),0),rebate=settled.reduce((sum,bet)=>sum+Number(bet.rebate||0),0),closing=settled.filter(bet=>bet.clv!=null);return{settled,profit,risk,rebate,roi:risk?profit/risk:0,avgClv:closing.length?closing.reduce((sum,bet)=>sum+bet.clv,0)/closing.length:null,w:settled.filter(bet=>Number(bet.fraction)>0).length,l:settled.filter(bet=>Number(bet.fraction)<0).length,p:settled.filter(bet=>Number(bet.fraction)===0).length}},[store.bets]);
  function exportJSON(){download(`mlb-positive-ev-${Date.now()}.json`,JSON.stringify(store,null,2))}
  function exportCSV(){const head=['時間','比賽','市場','投注方向','水位','評分','注碼單位','結果','盈虧','退水','收盤價值'];const rows=store.bets.map(bet=>[bet.createdAt,translateTeamText(bet.game),bet.market,translateTeamText(bet.pick),bet.water,bet.score,bet.unit,bet.result,bet.profit,bet.rebate,bet.clv]);download(`mlb-bets-${Date.now()}.csv`,[head,...rows].map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
  async function importJSON(file){try{const data=JSON.parse(await file.text());setStore({...EMPTY,...data,settings:{...DEFAULT_SETTINGS,...data.settings},analyses:{},locks:[]});alert('備份已還原；為避免舊模型殘留，請重新鎖定並分析')}catch{alert('備份檔格式錯誤')}}
  const scoreGroups=[['8.5 分以上',bet=>bet.score>=8.5],['8.0～8.4 分',bet=>bet.score>=8&&bet.score<8.5],['7.2～7.9 分',bet=>bet.score>=7.2&&bet.score<8],['低於 7.2 分',bet=>bet.score<7.2]];

  return <main className="shell">
    <header className="header"><div><div className="eyebrow">私人分析系統</div><h1>⚾ MLB 長期正期望值分析</h1><p>截圖辨識 → 盤口鎖定 → MLB 資料 → 實際開盤市場評估 → 下注績效</p></div><div className="headerRight"><span className={`health ${health?.ok&&health?.aiGatewayConfigured?'ok':'warn'}`}>{health?.ok?(health.aiGatewayConfigured?'人工智慧正常':'人工智慧未設定'):'系統檢查中'}</span><span className="badge">第 {VERSION} 版</span></div></header>
    <nav className="tabs">{[['today','今日賽事'],['upload','📷 上傳'],['confirm','盤口確認'],['analysis','分析結果'],['bets','下注紀錄'],['perf','績效'],['settings','設定']].map(([key,name])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{name}</button>)}</nav>

    {tab==='today'&&<section><div className="metrics"><Metric t="今日賽事" v={games.length}/><Metric t="已鎖定" v={store.locks.length}/><Metric t="下注候選" v={allResults.filter(result=>result.score>=store.settings.candidateThreshold).length}/><Metric t="最高評分" v={allResults.length?Math.max(...allResults.map(result=>result.score)).toFixed(1):'—'}/></div><div className="card toolbar"><input type="date" value={date} onChange={event=>setDate(event.target.value)}/><button className="primary" onClick={loadGames}>{loadingGames?'載入中…':'重新載入'}</button></div><div className="card"><h2>今日 MLB 賽事儀表板</h2>{!gameSummary.length?<Empty text="今天沒有賽事或尚未載入"/>:gameSummary.map(game=><div className="gameRow" key={game.gamePk}><div><b>{matchup(game)}</b><small>{new Date(game.gameDate).toLocaleString('zh-TW')}｜{game.venue}</small><small>先發投手（官方原文）：{game.awayProbable||'未公布'} 對 {game.homeProbable||'未公布'}</small></div><div className="gameStatus"><span className="pill">{game.status}</span><span>{game.analyzed?'已分析':game.locked?'已鎖定':'未分析'}</span><strong>{game.highest?.toFixed(1)||'—'}</strong></div></div>)}</div></section>}

    {tab==='upload'&&<section><div className="card"><h2>一、上傳信用盤截圖</h2><label className="drop">點這裡從手機相簿選擇<input type="file" accept="image/*" multiple onChange={event=>chooseImages(event.target.files)}/><span>最多 8 張；系統會逐張壓縮與辨識</span></label><div className="previews">{images.map(image=><div className="preview" key={image.id}><img src={image.preview} alt="盤口截圖"/><button onClick={()=>setImages(previous=>previous.filter(item=>item.id!==image.id))}>移除</button><small>{image.name}</small></div>)}</div><div className="status">{visionStatus||'尚未選擇圖片'}</div><button className="primary full" disabled={visionBusy||!images.length} onClick={recognize}>{visionBusy?'人工智慧辨識中，請勿重複點擊':'開始辨識盤口'}</button></div><div className="card"><h2>二、盤口文字備援</h2><textarea rows="7" value={manualText} onChange={event=>setManualText(event.target.value)} placeholder="可直接貼上整段盤口文字"/><button className="secondary full" disabled={visionBusy} onClick={parseText}>解析盤口文字</button></div><div className="card"><h2>三、手動建立空白賽事</h2><div className="toolbar"><select value={manualGamePk} onChange={event=>setManualGamePk(event.target.value)}><option value="">選擇今日賽事</option>{games.map(game=><option key={game.gamePk} value={game.gamePk}>{matchup(game)}</option>)}</select><button className="secondary" onClick={addManual}>建立</button></div></div></section>}

    {tab==='confirm'&&<section><div className="card"><h2>盤口確認與鎖定</h2>{!parsed.length?<Empty text="尚無辨識結果，請先到上傳頁"/>:<><div className="chips">{parsed.map((game,index)=><button key={game.id} className={index===selected?'chip activeChip':'chip'} onClick={()=>setSelected(index)}>{matchup(game)}</button>)}</div><label>配對 MLB 官方賽事<select value={cur?.matchedGame?.gamePk||''} onChange={event=>setMatch(event.target.value)}><option value="">請選擇</option>{games.map(game=><option key={game.gamePk} value={game.gamePk}>{matchup(game)}</option>)}</select></label>{MARKET_ORDER.map(market=>{const row=cur?.markets?.find(item=>item.market===market)||{directions:[]};const directions=[...(row.directions||[])];while(directions.length<2)directions.push({pick:'',water:store.settings.defaultWater,confidence:0});const open=marketIsOpen(directions);return <div className="market" key={market}><h3>{market} {!open&&<span className="pill">未開盤</span>}</h3><div className="two">{directions.slice(0,2).map((direction,index)=><div className="direction" key={index}><label>方向＋盤口<input value={direction.pick||''} onChange={event=>editDirection(market,index,'pick',event.target.value)}/></label><label>水位<input type="number" step=".001" value={direction.water??store.settings.defaultWater} onChange={event=>editDirection(market,index,'water',event.target.value)}/></label><small>辨識信心：{Math.round(Number(direction.confidence||0)*100)}%</small></div>)}</div></div>})}{currentErrors.length?<div className="errors">{currentErrors.map(error=><div key={error}>• {error}</div>)}</div>:currentOpenMarkets.length?<div className="success">✓ 已開 {currentOpenMarkets.length} 個市場、{currentDirectionCount} 個方向；空白市場視為未開盤</div>:<div className="warnings">目前沒有已開盤市場</div>}<button className="primary full" onClick={lockCurrent}>🔒 確認並鎖定</button></>}</div><div className="card"><h2>已鎖定盤口</h2>{!store.locks.length?<Empty text="尚無鎖定賽事"/>:store.locks.map(lock=><div className="locked" key={lock.id}><div><b>{matchup(lock.game)}</b><small>鎖定時間：{new Date(lock.lockedAt).toLocaleString('zh-TW')}｜{new Set(lock.markets.map(item=>item.market)).size} 個市場</small></div><button className="primary" onClick={()=>analyze(lock)}>開始分析</button></div>)}</div></section>}

    {tab==='analysis'&&<section>{!store.locks.length?<div className="card"><Empty text="尚無鎖定賽事"/></div>:store.locks.map(lock=>{const data=store.analyses[lock.id];return <div className="card analysisCard" key={lock.id}><div className="analysisHead"><div><h2>{matchup(lock.game)}</h2><small>先發投手（官方原文）：{lock.game.awayProbable||'未公布'} 對 {lock.game.homeProbable||'未公布'}</small></div><button className="secondary" onClick={()=>analyze(lock)}>{data?.loading?'分析中…':'重新分析'}</button></div>{data?.error&&<div className="errors">{data.error}</div>}{data?.loading&&<div className="status">正在取得先發、近期數據、打線、天氣與休息資料…</div>}{data?.ok&&<><Context context={data.context} analysis={data.analysis}/>{MARKET_ORDER.map(market=>{const rows=data.analysis.results.filter(result=>result.market===market);return <div className="market results" key={market}><h3>{market}</h3>{!rows.length?<Empty text="未開盤"/>:rows.map((result,index)=><div className={`result ${result.score>=store.settings.strongestThreshold?'best':result.score>=store.settings.candidateThreshold?'candidate':''}`} key={index}><div><div><span className="score">{result.score.toFixed(1)}</span>｜{translateTeamText(result.pick)}｜{Number(result.water).toFixed(3)} {result.tag&&<span className="tag">{result.tag}</span>}</div><small>校準過盤率 {pct(result.modelProbability)}｜校準期望值 {pct(result.ev)}｜穩健期望值 {pct(result.robustEV)}｜最終期望值 {pct(result.weightedEV)}</small><small>原始模型率 {pct(result.rawModelProbability)}｜資料可信度 {pct(result.confidence)}{result.edgeClipped?'｜極端值已收斂':''}</small><small>全贏 {pct(result.fullWinProbability)}｜部分贏 {pct(result.partialWinProbability)}｜走水 {pct(result.pushProbability)}</small></div><button onClick={()=>addBet(lock.game,result)}>記錄下注</button></div>)}</div>})}</>}</div>})}</section>}

    {tab==='bets'&&<section><div className="card"><h2>下注紀錄</h2>{!store.bets.length?<Empty text="尚無下注紀錄"/>:<div className="betList">{store.bets.map(bet=><div className="betCard" key={bet.id}><div className="betTop"><div><b>{translateTeamText(bet.game)}</b><small>{bet.market}｜{translateTeamText(bet.pick)}｜{Number(bet.water).toFixed(3)}｜評分 {Number(bet.score).toFixed(1)}</small><small>下注時間：{new Date(bet.createdAt).toLocaleString('zh-TW')}</small></div><button className="dangerSmall" onClick={()=>removeBet(bet.id)}>刪除</button></div><div className="betGrid"><label>注碼單位<input type="number" step=".1" value={bet.unit} onChange={event=>updateBet(bet.id,{unit:Number(event.target.value),stake:Number(event.target.value)*store.settings.unitValue})}/></label>{bet.market.includes('上半')?<><label>客隊上半得分<input type="number" value={bet.awayFirst5} onChange={event=>updateBet(bet.id,{awayFirst5:event.target.value})}/></label><label>主隊上半得分<input type="number" value={bet.homeFirst5} onChange={event=>updateBet(bet.id,{homeFirst5:event.target.value})}/></label></>:<><label>客隊得分<input type="number" value={bet.awayRuns} onChange={event=>updateBet(bet.id,{awayRuns:event.target.value})}/></label><label>主隊得分<input type="number" value={bet.homeRuns} onChange={event=>updateBet(bet.id,{homeRuns:event.target.value})}/></label></>}<label>收盤水位<input type="number" step=".001" value={bet.closeWater} onChange={event=>updateBet(bet.id,{closeWater:event.target.value})}/></label><label>收盤盤口<input value={bet.closePick} onChange={event=>updateBet(bet.id,{closePick:event.target.value})}/></label></div><div className="toolbar"><button className="secondary" onClick={()=>settleBet(bet)}>依比分結算</button><button className="secondary" onClick={()=>autoSettle(bet)}>自動抓取終場</button><span className={`settle ${Number(bet.profit)>=0?'positive':'negative'}`}>{bet.result}｜{money(bet.profit)}｜退水 {money(bet.rebate)}{bet.clv!=null?`｜收盤價值 ${pct(bet.clv)}`:''}</span></div></div>)}</div>}</div></section>}

    {tab==='perf'&&<section><div className="metrics"><Metric t="總下注" v={store.bets.length}/><Metric t="已結算" v={perf.settled.length}/><Metric t="勝／敗／走" v={`${perf.w}/${perf.l}/${perf.p}`}/><Metric t="投資報酬率" v={pct(perf.roi)}/><Metric t="總盈虧" v={money(perf.profit)}/><Metric t="總退水" v={money(perf.rebate)}/><Metric t="平均收盤價值" v={perf.avgClv==null?'—':pct(perf.avgClv)}/></div><div className="card"><h2>評分區間</h2><GroupTable groups={scoreGroups.map(([name,filter])=>[name,store.bets.filter(filter)])}/></div><div className="card"><h2>市場統計</h2><GroupTable groups={MARKET_ORDER.map(market=>[market,store.bets.filter(bet=>bet.market===market)])}/></div><div className="card"><h2>球隊統計</h2><GroupTable groups={[...new Set(store.bets.flatMap(bet=>[bet.away,bet.home]).filter(Boolean))].map(team=>[translateTeamText(team),store.bets.filter(bet=>bet.away===team||bet.home===team)])}/></div></section>}

    {tab==='settings'&&<section><div className="card"><h2>系統設定</h2><div className="settingsGrid"><Setting label="一個注碼單位金額" value={store.settings.unitValue} step="1000" onChange={value=>setStore(current=>({...current,settings:{...current.settings,unitValue:Number(value)}}))}/><Setting label="每萬退水比例" value={store.settings.rebateRate} step=".001" onChange={value=>setStore(current=>({...current,settings:{...current.settings,rebateRate:Number(value)}}))}/><Setting label="預設水位" value={store.settings.defaultWater} step=".001" onChange={value=>setStore(current=>({...current,settings:{...current.settings,defaultWater:Number(value)}}))}/><Setting label="下注候選門檻" value={store.settings.candidateThreshold} step=".1" onChange={value=>setStore(current=>({...current,settings:{...current.settings,candidateThreshold:Number(value)}}))}/><Setting label="最強主推門檻" value={store.settings.strongestThreshold} step=".1" onChange={value=>setStore(current=>({...current,settings:{...current.settings,strongestThreshold:Number(value)}}))}/></div></div><div className="card"><h2>備份與資料</h2><div className="toolbar wrap"><button className="secondary" onClick={exportJSON}>匯出 JSON 備份</button><button className="secondary" onClick={exportCSV}>匯出 CSV 明細</button><label className="fileButton">匯入 JSON 備份<input type="file" accept="application/json" onChange={event=>event.target.files?.[0]&&importJSON(event.target.files[0])}/></label><button className="danger" onClick={()=>{if(confirm('確定清除全部下注、分析與鎖定資料？'))setStore({...EMPTY,settings:store.settings})}}>清除資料</button></div><p className="note">資料目前保存在這台手機的瀏覽器內，請定期匯出 JSON 備份。每次模型大改版後，舊分析會自動清除，避免舊評分混入新版本。</p></div></section>}
  </main>
}

function Metric({t,v}){return <div className="metric"><span>{t}</span><b>{v}</b></div>}
function Empty({text}){return <div className="empty">{text}</div>}
function Setting({label,value,onChange,step}){return <label>{label}<input type="number" value={value} step={step} onChange={event=>onChange(event.target.value)}/></label>}
function Context({context,analysis}){const away=context.away,home=context.home;return <><div className="contextGrid"><Info t="先發投手（官方原文）" v={`${away.starter?.name||'未確認'} 對 ${home.starter?.name||'未確認'}`}/><Info t="預估比分" v={`全場 ${analysis.expectedRuns.full.away.toFixed(2)}－${analysis.expectedRuns.full.home.toFixed(2)}｜上半 ${analysis.expectedRuns.first5.away.toFixed(2)}－${analysis.expectedRuns.first5.home.toFixed(2)}`}/><Info t="打線／捕手（官方原文）" v={`${away.lineup?.official?'正式':'預估'} ${away.lineup?.catcher||'—'}｜${home.lineup?.official?'正式':'預估'} ${home.lineup?.catcher||'—'}`}/><Info t="牛棚疲勞代理值" v={`客隊 ${Math.round((away.bullpen?.fatigueIndex||0)*100)}%｜主隊 ${Math.round((home.bullpen?.fatigueIndex||0)*100)}%`}/><Info t="傷停人數" v={`客隊 ${away.injuriesAvailable?(away.injuries?.length||0):'未取得'}｜主隊 ${home.injuriesAvailable?(home.injuries?.length||0):'未取得'}`}/><Info t="球場／天氣" v={`${context.park?.name||'—'}（${context.park?.roofZh||'屋頂狀態未知'}）｜${context.weather?.available?`${context.weather.temperature}°C、風速 ${context.weather.windSpeed} 公里／小時`:'未取得'}`}/><Info t="旅行與休息" v={`客隊休 ${away.rest?.days??'—'} 天／${away.rest?.travelKm||0} 公里｜主隊休 ${home.rest?.days??'—'} 天／${home.rest?.travelKm||0} 公里`}/><Info t="主審（官方原文）／資料品質" v={`${context.umpire||'未公布'}｜${Math.round(analysis.dataQuality*100)}%`}/><Info t="模型版本" v={analysis.modelVersion||'保守校準模型'}/></div>{context.warnings?.length>0&&<div className="warnings">{context.warnings.join('；')}</div>}</>}
function Info({t,v}){return <div className="info"><span>{t}</span><b>{v}</b></div>}
function GroupTable({groups}){return <div className="groupTable">{groups.filter(([,rows])=>rows.length).map(([name,rows])=>{const settled=rows.filter(bet=>bet.fraction!=null),profit=settled.reduce((sum,bet)=>sum+Number(bet.profit||0),0),risk=settled.reduce((sum,bet)=>sum+Number(bet.stake||0),0);return <div key={name}><b>{name}</b><span>{rows.length} 筆</span><span>{settled.length} 筆已結算</span><span>投資報酬率 {pct(risk?profit/risk:0)}</span><span>{money(profit)}</span></div>})}</div>}
