'use client';
import {useEffect,useState} from 'react';
import styles from './nba.module.css';
const reasons={POSTPONED_OR_CANCELLED:'延期或取消',PLAYER_EVIDENCE_BLOCKED_NOT_USED:'球員身分未通過，研究僅用球隊統計',GAME_IDENTITY_UNRESOLVED:'比賽尚未配對',VERIFIED_BOXSCORE_MISSING:'完整比賽統計缺失',MODEL_QA_BLOCK:'模型資料核對未通過',WARMUP_OR_INSUFFICIENT_HISTORY:'訓練場數不足',MARKET_PERIOD_UNVERIFIED:'盤口時段待確認',ODDS_CAPTURE_TIME_MISSING:'缺少盤口擷取時間'};
const n=v=>Number.isFinite(v)?v.toFixed(2):'—';
export default function CorpusPanel(){
 const [opened,setOpened]=useState(false),[page,setPage]=useState(1),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState(null),[saving,setSaving]=useState(false),[receipt,setReceipt]=useState(null),[revision,setRevision]=useState(0);
 async function importReport(){if(!upload)return;setSaving(true);setError('');setReceipt(null);try{if(upload.size>3500000)throw Error('研究報告過大');const body=await upload.text();const r=await fetch('/api/nba/corpus',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body});const value=await r.json();if(!r.ok||!value.receipt?.persisted)throw Error(value.error||'尚未成功保存');setReceipt(value.receipt);setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setSaving(false);}}
 useEffect(()=>{if(!opened)return;const abort=new AbortController();setBusy(true);setError('');
 fetch(`/api/nba/corpus?${new URLSearchParams({page:String(page),q:query,status})}`,{credentials:'same-origin',cache:'no-store',signal:abort.signal}).then(async r=>{const body=await r.json();if(!r.ok||body.league!=='NBA')throw Error('無法取得盤口歷史研究');return body;}).then(d=>{if(!abort.signal.aborted)setData(d);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[opened,page,query,status,revision]);
 return <section className={styles.panel} aria-label="NBA 全部歷史盤口研究"><h2>全部歷史盤口研究</h2><p>342 張來源圖片。逐場保留配對、模型研究與盤口證據狀態。</p><button onClick={()=>setOpened(v=>!v)}>{opened?'收合盤口研究':'查看全部歷史盤口'}</button>{opened&&<>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">讀取中…</p>}
 <details><summary>匯入歷史研究報告</summary><p>保存為獨立研究版本，不會改寫賽前快照或正式模型。</p><input type="file" accept="application/json,.json" aria-label="歷史研究 JSON 檔案" onChange={e=>setUpload(e.target.files?.[0]||null)}/><button disabled={!upload||saving} onClick={importReport}>{saving?'保存中…':'保存研究報告'}</button>{receipt&&<p role="status">已保存並讀回核對 {receipt.candidateGames} 場；版本 {receipt.revision.slice(0,12)}</p>}</details>{data?.empty&&<p>尚未匯入歷史盤口研究報告。</p>}
 {data&&!data.empty&&<><p>候選賽事 <strong>{data.summary.candidateGames}</strong> 場；原始快照 {data.summary.rawSnapshots} 筆；市場資料 {data.summary.marketRecords} 組。</p><p>來源賽程已配對 {data.summary.providerMatched} 場；納入比分逐時驗證 {data.summary.researchIncluded} 場；尚未納入 {data.summary.candidateGames-data.summary.researchIncluded} 場。</p><p>這批場次模型 MAE {n(data.metrics?.model?.mae)}；同場基準 MAE {n(data.metrics?.baseline?.mae)}。每場固定使用主隊模型，數值越低越好。</p><p>盤口績效回測通過 {data.summary.marketBacktestEligible} 場。比分研究不等於盤口回測；尚缺時段與擷取時間證據，未計算勝率、EV 或盈虧。</p>
 <label>搜尋日期或隊伍 <input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="例如 CLE、2026-03"/></label>{' '}<label>研究狀態 <select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">全部場次</option><option value="included">已納入比分驗證</option><option value="pending">尚未納入</option></select></label>
 {!busy&&<><p>符合條件 {data.total} 場</p><div style={{overflowX:'auto'}}><table className={styles.corpusTable}><thead><tr><th>候選日期</th><th>客隊／主隊</th><th>比分研究</th><th>快照／原始盤口</th><th>待補項目</th></tr></thead><tbody>{data.entries.map(e=><tr key={e.key}><td>{e.candidateDate}</td><td>{e.away} @ {e.home}</td><td>{e.researchStatus==='included_home_team_chronological_fold'?'已納入':'待完成'}</td><td><details><summary>{e.snapshotCount} 筆盤口</summary>{e.marketQuotes?.map(q=><p key={q.sourceRow}>{q.sourceRow}：{q.favorite||'—'} {q.spread||'—'}；大小 {q.total||'—'}；主／客水位 {q.homeOdds||'—'}／{q.awayOdds||'—'}；大／小水位 {q.overOdds||'—'}／{q.underOdds||'—'}</p>)}{e.fold?.historicalDiagnostics&&<p>歷史預估（客：主）{n(e.fold.historicalDiagnostics.predictedOpponent)}：{n(e.fold.historicalDiagnostics.predictedOwn)}；實際 {e.fold.historicalDiagnostics.actualOpponent}：{e.fold.historicalDiagnostics.actualOwn}</p>}</details></td><td>{e.reasons.map(r=>reasons[r]||r).join('、')}</td></tr>)}</tbody></table></div><button disabled={data.page<=1} onClick={()=>setPage(data.page-1)}>上一頁</button><span> {data.page} / {data.pages} </span><button disabled={data.page>=data.pages} onClick={()=>setPage(data.page+1)}>下一頁</button></>}
 <p>更新：{data.generatedAt}。球季與配對使用 ESPN 次級來源，官方 ID 仍待核對；不宣稱嚴格賽前重播或模型優於基準。</p></>}
 </>}</section>;
}
